---
# basic parameters
nx: 40
ny: 40
nsampling: 4 # sampling inverval

# data
# type_sr: point or line
type_sr: line

file_src: source.txt
file_rec: receiver.txt

source: [[1, 1], [39, 39], [2, 2]]
receiver: [[1, 1], [39, 39], [2, 2]]


# model
model: checkboard

checkboard:
  nx: 2
  ny: 2
  vref: 0.15
  vmax: 0.003

# inversion algorithm:
#       CG
#       LBFGS
#       DE1
#       DE2
# DE1 is de from scipy (slow)
# DE2 is de from pygmo
#
algorithm: LBFGS

# DE paras
bounds_percentage: 0.05
gen: 2000
